CREATE SCHEMA IF NOT EXISTS spring6jdbc3;

SET SCHEMA spring6jdbc3;

CREATE TABLE IF NOT EXISTS speakers (
    id IDENTITY NOT NULL PRIMARY KEY ,
    name VARCHAR(100) NOT NULL
);

ALTER TABLE speakers ADD COLUMN IF NOT EXISTS skill VARCHAR(100)